package com.example.entity;

import javax.persistence.*;

/**
 * This is a class that models a Comment.
 */
@Entity
@Table(name = "comment")
public class Comment {

    @Column(name = "commentId")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer commentId;

    @Column(name = "postedBy")
    private Integer postedBy;

    @Column(name = "messageId")
    private Integer messageId;

    @Column(name = "commentText")
    private String commentText;

    @Column(name = "timePostedEpoch")
    private Long timePostedEpoch;

    public Comment() {
    }

    /**
     * When posting a new comment, the id can be generated by the database. In that
     * case, a constructor without
     * commentId is needed.
     *
     * @param postedBy        the ID of the user posting the comment
     * @param messageId       the ID of the message being commented on
     * @param commentText     the text of the comment
     * @param timePostedEpoch the epoch time when the comment was posted
     */
    public Comment(Integer postedBy, Integer messageId, String commentText, Long timePostedEpoch) {
        this.postedBy = postedBy;
        this.messageId = messageId;
        this.commentText = commentText;
        this.timePostedEpoch = timePostedEpoch;
    }

    public Comment(Integer commentId, Integer postedBy, Integer messageId, String commentText, Long timePostedEpoch) {
        this.commentId = commentId;
        this.postedBy = postedBy;
        this.messageId = messageId;
        this.commentText = commentText;
        this.timePostedEpoch = timePostedEpoch;
    }

    // Getters and setters for all fields
    public Integer getCommentId() {
        return commentId;
    }

    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    public Integer getPostedBy() {
        return postedBy;
    }

    public void setPostedBy(Integer postedBy) {
        this.postedBy = postedBy;
    }

    public Integer getMessageId() {
        return messageId;
    }

    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    public String getCommentText() {
        return commentText;
    }

    public void setCommentText(String commentText) {
        this.commentText = commentText;
    }

    public Long getTimePostedEpoch() {
        return timePostedEpoch;
    }

    public void setTimePostedEpoch(Long timePostedEpoch) {
        this.timePostedEpoch = timePostedEpoch;
    }

    
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Comment other = (Comment) obj;
        if (commentId == null) {
            if (other.commentId != null)
                return false;
        } else if (!commentId.equals(other.commentId))
            return false;
        if (commentText == null) {
            if (other.commentText != null)
                return false;
        } else if (!commentText.equals(other.commentText))
            return false;
        if (postedBy == null) {
            if (other.postedBy != null)
                return false;
        } else if (!postedBy.equals(other.postedBy))
            return false;
        if (timePostedEpoch == null) {
            if (other.timePostedEpoch != null)
                return false;
        } else if (!timePostedEpoch.equals(other.timePostedEpoch))
            return false;
        if (messageId == null) {
            if (other.messageId != null)
                return false;
        } else if (!messageId.equals(other.messageId))
            return false;
        return true;
    }

    @Override
    public String toString() {
        return "Comment{" +
                "commentId=" + commentId +
                ", postedBy=" + postedBy +
                ", messageId=" + messageId +
                ", commentText='" + commentText + '\'' +
                ", timePostedEpoch=" + timePostedEpoch +
                '}';
    }
}